import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import dotenv from 'dotenv';

dotenv.config();

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const initialDpsList = [
  {
    id: "dps-001",
    status: "Calon DPS",
    jenisPenugasan: "Penuh Waktu",
    tanggalPengajuan: "2026-05-16",
    namaLengkap: "Dr. Ahmad Zaki, M.A.",
    tempatLahir: "Jakarta",
    tanggalLahir: "1975-01-12",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "12.345.678.9-012.000",
    alamatDomisili: "Jl. Tebet Timur Dalam II No. 45, Tebet, Jakarta Selatan, DKI Jakarta",
    rtRw: "004 / 008",
    kelurahan: "Tebet Timur",
    kecamatan: "Tebet",
    kotaKabupaten: "Jakarta Selatan",
    provinsi: "DKI Jakarta",
    kodePos: "12820",
    noTelepon: "021-83783783",
    noHp: "0812-1234-5678",
    email: "ahmad.zaki@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Ekonomi Islam",
    perguruanTinggi: "Universitas Indonesia",
    tahunLulus: "2010",
    lembagaPenempatan: "Bank Syariah Indonesia",
    jabatanDps: "Anggota",
    skPengangkatan: "SK-DSN-MUI/X/2026/001",
    tanggalSk: "2026-05-10",
    masaJabatanMulai: "2026-05-10",
    masaJabatanSelesai: "2031-05-10",
    riwayatJabatan: [
      { lembaga: "Bank Mandiri Syariah", jabatan: "DPS", periode: "2018 - 2021" }
    ],
    sertifikatPelatihan: [
      { nama: "Sertifikasi DPS Level 1", lembaga: "DSN-MUI Institute", tahun: "2015" }
    ],
    bidangKeahlian: ["Fikih Muamalah", "Perbankan Syariah"],
    pengalamanProfesional: "Dosen Pascasarjana Ekonomi Syariah UI and peneliti senior ekonomi Islam."
  },
  {
    id: "dps-002",
    status: "Aktif",
    jenisPenugasan: "Penuh Waktu",
    tanggalPengajuan: "2026-04-12",
    namaLengkap: "Prof. Dr. KH. M. Cholil Nafis, Lc., M.A.",
    tempatLahir: "Sampang",
    tanggalLahir: "1975-06-01",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "21.543.876.1-015.000",
    alamatDomisili: "Jl. Pesantren No. 1, Jagakarsa, Jakarta Selatan",
    rtRw: "001 / 002",
    kelurahan: "Jagakarsa",
    kecamatan: "Jagakarsa",
    kotaKabupaten: "Jakarta Selatan",
    provinsi: "DKI Jakarta",
    kodePos: "12620",
    noTelepon: "021-7890123",
    noHp: "0811-987-654",
    email: "cholil.nafis@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Dirasat Islamiyah",
    perguruanTinggi: "Universitas Malaya",
    tahunLulus: "2010",
    lembagaPenempatan: "Bank Syariah Indonesia",
    jabatanDps: "Ketua",
    skPengangkatan: "SK-DSN-MUI/VIII/2025/112",
    tanggalSk: "2025-08-15",
    masaJabatanMulai: "2025-08-15",
    masaJabatanSelesai: "2030-08-15",
    riwayatJabatan: [
      { lembaga: "BNI Syariah", jabatan: "Ketua DPS", periode: "2015 - 2021" }
    ],
    sertifikatPelatihan: [
      { nama: "Sertifikasi Pengawas Syariah Utama", lembaga: "DSN-MUI", tahun: "2012" }
    ],
    bidangKeahlian: ["Fikih Muamalah", "Pasar Modal Syariah"],
    pengalamanProfesional: "Ketua MUI Bidang Dakwah dan Ukhuwah, berpengalaman mengawasi berbagai LKS tingkat nasional."
  },
  {
    id: "dps-003",
    status: "Aktif",
    jenisPenugasan: "Paruh Waktu",
    tanggalPengajuan: "2026-03-20",
    namaLengkap: "Dr. H. Anwar Abbas, M.M., M.Ag.",
    tempatLahir: "Lima Puluh Kota",
    tanggalLahir: "1955-02-15",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "34.123.456.7-013.000",
    alamatDomisili: "Jl. Kembang Raya No. 12, Kembangan, Jakarta Barat",
    rtRw: "005 / 006",
    kelurahan: "Kembangan Utara",
    kecamatan: "Kembangan",
    kotaKabupaten: "Jakarta Barat",
    provinsi: "DKI Jakarta",
    kodePos: "11610",
    noTelepon: "021-5801234",
    noHp: "0812-345-6789",
    email: "anwar.abbas@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Syariah",
    perguruanTinggi: "UIN Syarif Hidayatullah",
    tahunLulus: "2008",
    lembagaPenempatan: "PT Pegadaian Syariah",
    jabatanDps: "Ketua",
    skPengangkatan: "SK-DSN-MUI/I/2026/020",
    tanggalSk: "2026-01-20",
    masaJabatanMulai: "2026-01-20",
    masaJabatanSelesai: "2031-01-20",
    riwayatJabatan: [
      { lembaga: "Bank Muamalat", jabatan: "Anggota DPS", periode: "2010 - 2018" }
    ],
    sertifikatPelatihan: [
      { nama: "Workshop Audit Syariah Komprehensif", lembaga: "IADI", tahun: "2014" }
    ],
    bidangKeahlian: ["Makroekonomi Islam", "Lembaga Keuangan Mikro"],
    pengalamanProfesional: "Wakil Ketua Umum MUI, mantan Sekretaris Jenderal MUI, pakar ekonomi Islam Indonesia."
  },
  {
    id: "dps-004",
    status: "Aktif",
    jenisPenugasan: "Penuh Waktu",
    tanggalPengajuan: "2026-05-01",
    namaLengkap: "Dr. Oni Sahroni, M.A.",
    tempatLahir: "Bandung",
    tanggalLahir: "1975-12-05",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "45.987.654.3-014.000",
    alamatDomisili: "Perumahan Dosen UI No. B-12, Depok, Jawa Barat",
    rtRw: "002 / 011",
    kelurahan: "Kukusan",
    kecamatan: "Beji",
    kotaKabupaten: "Depok",
    provinsi: "Jawa Barat",
    kodePos: "16425",
    noTelepon: "021-7270001",
    noHp: "0813-1111-2222",
    email: "oni.sahroni@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Fikih Perbandingan",
    perguruanTinggi: "Universitas Al-Azhar Kairo",
    tahunLulus: "2009",
    lembagaPenempatan: "Muamalat Institut / Bank Muamalat",
    jabatanDps: "Anggota",
    skPengangkatan: "SK-DSN-MUI/XI/2024/099",
    tanggalSk: "2024-11-15",
    masaJabatanMulai: "2024-11-15",
    masaJabatanSelesai: "2029-11-15",
    riwayatJabatan: [],
    sertifikatPelatihan: [
      { nama: "Sertifikasi DPS Pasar Modal", lembaga: "OJK & DSN-MUI", tahun: "2016" }
    ],
    bidangKeahlian: ["Fikih Kontemporer", "Muamalah Maliyah"],
    pengalamanProfesional: "Anggota BPH DSN-MUI, pakar fikih keuangan syariah kontemporer, konsultan syariah nasional."
  },
  {
    id: "dps-005",
    status: "Aktif",
    jenisPenugasan: "Paruh Waktu",
    tanggalPengajuan: "2026-04-18",
    namaLengkap: "Dr. Irfan Syauqi Beik",
    tempatLahir: "Bogor",
    tanggalLahir: "1979-05-19",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "56.456.789.0-011.000",
    alamatDomisili: "Jl. Pajajaran No. 88, Bogor, Jawa Barat",
    rtRw: "003 / 004",
    kelurahan: "Baranangsiang",
    kecamatan: "Bogor Timur",
    kotaKabupaten: "Bogor",
    provinsi: "Jawa Barat",
    kodePos: "16143",
    noTelepon: "0251-8321234",
    noHp: "0812-9999-8888",
    email: "irfan.beik@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Ekonomi Islam",
    perguruanTinggi: "International Islamic University Malaysia",
    tahunLulus: "2010",
    lembagaPenempatan: "BAZNAS",
    jabatanDps: "Anggota",
    skPengangkatan: "SK-DSN-MUI/V/2025/042",
    tanggalSk: "2025-05-10",
    masaJabatanMulai: "2025-05-10",
    masaJabatanSelesai: "2030-05-10",
    riwayatJabatan: [],
    sertifikatPelatihan: [
      { nama: "Pelatihan Zakat Internasional", lembaga: "World Zakat Forum", tahun: "2018" }
    ],
    bidangKeahlian: ["Ekonomi Pembangunan Islam", "Zakat & Wakaf"],
    pengalamanProfesional: "Dosen IPB University, pengurus pusat Ikatan Ahli Ekonomi Islam (IAEI)."
  },
  {
    id: "dps-006",
    status: "Nonaktif",
    jenisPenugasan: "Penuh Waktu",
    tanggalPengajuan: "2026-01-10",
    namaLengkap: "Dr. KH. Ahzami Samiun Jazuli, M.A.",
    tempatLahir: "Pati",
    tanggalLahir: "1962-06-15",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "67.890.123.4-012.000",
    alamatDomisili: "Jl. Raya Jatiwaringin No. 24, Pondok Gede, Bekasi",
    rtRw: "004 / 005",
    kelurahan: "Jatiwaringin",
    kecamatan: "Pondok Gede",
    kotaKabupaten: "Bekasi",
    provinsi: "Jawa Barat",
    kodePos: "17411",
    noTelepon: "021-8461234",
    noHp: "0811-222-333",
    email: "ahzami.jazuli@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Tafsir Hadis",
    perguruanTinggi: "Universitas Islam Madinah",
    tahunLulus: "1999",
    lembagaPenempatan: "Asuransi Syariah Keluarga",
    jabatanDps: "Ketua",
    skPengangkatan: "SK-DSN-MUI/III/2021/014",
    tanggalSk: "2021-03-01",
    masaJabatanMulai: "2021-03-01",
    masaJabatanSelesai: "2026-03-01",
    riwayatJabatan: [],
    sertifikatPelatihan: [],
    bidangKeahlian: ["Tafsir Ahkam", "Syarah Hadis Muamalah"],
    pengalamanProfesional: "Pendiri Pesantren Yapidh, dosen senior tafsir Al-Qur'an."
  },
  {
    id: "dps-007",
    status: "Calon DPS",
    jenisPenugasan: "Paruh Waktu",
    tanggalPengajuan: "2026-05-15",
    namaLengkap: "Dr. Asep Supyadillah, M.Ag.",
    tempatLahir: "Purwakarta",
    tanggalLahir: "1980-04-12",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "78.901.234.5-015.000",
    alamatDomisili: "Perumahan Bukit Indah, Ciputat, Tangerang Selatan",
    rtRw: "008 / 009",
    kelurahan: "Ciputat",
    kecamatan: "Ciputat",
    kotaKabupaten: "Tangerang Selatan",
    provinsi: "Banten",
    kodePos: "15411",
    noTelepon: "021-7401234",
    noHp: "0813-8888-9999",
    email: "asep.supyadillah@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Syariah",
    perguruanTinggi: "UIN Syarif Hidayatullah",
    tahunLulus: "2015",
    lembagaPenempatan: "Koperasi Syariah Benteng Mikro Indonesia",
    jabatanDps: "Anggota",
    skPengangkatan: "",
    tanggalSk: "",
    masaJabatanMulai: "",
    masaJabatanSelesai: "",
    riwayatJabatan: [],
    sertifikatPelatihan: [
      { nama: "Sertifikasi DPS Lembaga Keuangan Mikro", lembaga: "DSN-MUI", tahun: "2021" }
    ],
    bidangKeahlian: ["Fiqh Muamalah", "Microfinance Syariah"],
    pengalamanProfesional: "Dosen Ekonomi Syariah UIN Jakarta, Sekretaris Asosiasi Dosen Ekonomi Syariah."
  },
  {
    id: "dps-008",
    status: "Aktif",
    jenisPenugasan: "Penuh Waktu",
    tanggalPengajuan: "2026-02-28",
    namaLengkap: "Dr. H. Hasanudin, M.Ag.",
    tempatLahir: "Cirebon",
    tanggalLahir: "1968-09-18",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "89.012.345.6-013.000",
    alamatDomisili: "Jl. Cempaka Putih Tengah XVII No. 4, Jakarta Pusat",
    rtRw: "002 / 003",
    kelurahan: "Cempaka Putih Timur",
    kecamatan: "Cempaka Putih",
    kotaKabupaten: "Jakarta Pusat",
    provinsi: "DKI Jakarta",
    kodePos: "10510",
    noTelepon: "021-4241234",
    noHp: "0812-7777-6666",
    email: "hasanudin@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Kajian Islam/Syariah",
    perguruanTinggi: "UIN Syarif Hidayatullah",
    tahunLulus: "2012",
    lembagaPenempatan: "PT Bank Danamon Indonesia Tbk (UUS)",
    jabatanDps: "Ketua",
    skPengangkatan: "SK-DSN-MUI/II/2024/011",
    tanggalSk: "2024-02-12",
    masaJabatanMulai: "2024-02-12",
    masaJabatanSelesai: "2029-02-12",
    riwayatJabatan: [],
    sertifikatPelatihan: [
      { nama: "Advanced Syariah Compliance", lembaga: "IBFI", tahun: "2018" }
    ],
    bidangKeahlian: ["Struktur Produk Syariah", "Audit Kepatuhan Syariah"],
    pengalamanProfesional: "Wakil Sekretaris BPH DSN-MUI, aktif merumuskan fatwa-fatwa keuangan kontemporer."
  },
  {
    id: "dps-009",
    status: "Aktif",
    jenisPenugasan: "Paruh Waktu",
    tanggalPengajuan: "2026-03-05",
    namaLengkap: "Prof. Dr. KH. Didin Hafidhuddin, MS",
    tempatLahir: "Bogor",
    tanggalLahir: "1951-10-21",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "90.123.456.7-011.000",
    alamatDomisili: "Jl. Pamoyanan, Bogor Selatan",
    rtRw: "001 / 001",
    kelurahan: "Pamoyanan",
    kecamatan: "Bogor Selatan",
    kotaKabupaten: "Bogor",
    provinsi: "Jawa Barat",
    kodePos: "16136",
    noTelepon: "0251-8211234",
    noHp: "0811-123-456",
    email: "didin.hafidhuddin@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Tafsir Syariah",
    perguruanTinggi: "UIN Syarif Hidayatullah",
    tahunLulus: "1998",
    lembagaPenempatan: "Bank Syariah Indonesia",
    jabatanDps: "Anggota",
    skPengangkatan: "SK-DSN-MUI/VII/2025/085",
    tanggalSk: "2025-07-01",
    masaJabatanMulai: "2025-07-01",
    masaJabatanSelesai: "2030-07-01",
    riwayatJabatan: [
      { lembaga: "BAZNAS", jabatan: "Ketua", periode: "2005 - 2015" }
    ],
    sertifikatPelatihan: [],
    bidangKeahlian: ["Manajemen Zakat", "Tafsir Ayat Muamalah"],
    pengalamanProfesional: "Guru Besar Universitas Ibn Khaldun Bogor, mantan Ketua Umum BAZNAS RI."
  },
  {
    id: "dps-010",
    status: "Aktif",
    jenisPenugasan: "Penuh Waktu",
    tanggalPengajuan: "2026-04-20",
    namaLengkap: "Dr. KH. M. Asrorun Niam Sholeh, M.A.",
    tempatLahir: "Nganjuk",
    tanggalLahir: "1976-05-31",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "11.222.333.4-012.000",
    alamatDomisili: "Perumahan Permata Puri, Depok, Jawa Barat",
    rtRw: "003 / 008",
    kelurahan: "Radar Auri",
    kecamatan: "Cimanggis",
    kotaKabupaten: "Depok",
    provinsi: "Jawa Barat",
    kodePos: "16452",
    noTelepon: "021-8770123",
    noHp: "0812-888-777",
    email: "niam.sholeh@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Hukum Islam",
    perguruanTinggi: "UIN Syarif Hidayatullah",
    tahunLulus: "2008",
    lembagaPenempatan: "PT Bank Mega Syariah",
    jabatanDps: "Ketua",
    skPengangkatan: "SK-DSN-MUI/X/2024/078",
    tanggalSk: "2024-10-10",
    masaJabatanMulai: "2024-10-10",
    masaJabatanSelesai: "2029-10-10",
    riwayatJabatan: [],
    sertifikatPelatihan: [
      { nama: "Sertifikasi DPS Perbankan Utama", lembaga: "DSN-MUI", tahun: "2013" }
    ],
    bidangKeahlian: ["Hukum Syariah Kontemporer", "Perlindungan Anak"],
    pengalamanProfesional: "Ketua MUI Bidang Fatwa, Deputi Kemenpora, Dosen Fakultas Syariah UIN Jakarta."
  },
  {
    id: "dps-011",
    status: "Calon DPS",
    jenisPenugasan: "Paruh Waktu",
    tanggalPengajuan: "2026-05-18",
    namaLengkap: "Dr. H. M. Zainul Majdi, M.A. (TGB)",
    tempatLahir: "Pancor",
    tanggalLahir: "1972-05-31",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "22.333.444.5-014.000",
    alamatDomisili: "Mataram, Nusa Tenggara Barat",
    rtRw: "001 / 001",
    kelurahan: "Pancor",
    kecamatan: "Selong",
    kotaKabupaten: "Lombok Timur",
    provinsi: "Nusa Tenggara Barat",
    kodePos: "83611",
    noTelepon: "0370-621234",
    noHp: "0811-777-888",
    email: "tgb.zainulmajdi@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Tafsir dan Ilmu Al-Qur'an",
    perguruanTinggi: "Universitas Al-Azhar Kairo",
    tahunLulus: "2011",
    lembagaPenempatan: "Bank NTB Syariah",
    jabatanDps: "Ketua",
    skPengangkatan: "",
    tanggalSk: "",
    masaJabatanMulai: "",
    masaJabatanSelesai: "",
    riwayatJabatan: [],
    sertifikatPelatihan: [],
    bidangKeahlian: ["Tafsir Al-Qur'an", "Keuangan Publik Islam"],
    pengalamanProfesional: "Gubernur NTB 2 periode (2008-2018), Ulama & Pakar Tafsir, Ketua Umum PB NWDI."
  },
  {
    id: "dps-012",
    status: "Aktif",
    jenisPenugasan: "Penuh Waktu",
    tanggalPengajuan: "2026-03-12",
    namaLengkap: "H. Ikhsan Abdullah, S.H., M.H.",
    tempatLahir: "Tangerang",
    tanggalLahir: "1965-03-24",
    jenisKelamin: "Laki-laki",
    kewarganegaraan: "Indonesia",
    agama: "Islam",
    npwp: "33.444.555.6-015.000",
    alamatDomisili: "Jl. Kebon Sirih No. 40, Jakarta Pusat",
    rtRw: "002 / 001",
    kelurahan: "Gambir",
    kecamatan: "Gambir",
    kotaKabupaten: "Jakarta Pusat",
    provinsi: "DKI Jakarta",
    kodePos: "10110",
    noTelepon: "021-3511234",
    noHp: "0812-444-555",
    email: "ikhsan.abdullah@dsnmui.or.id",
    pendidikanTerakhir: "S3 - Hukum",
    perguruanTinggi: "Universitas Indonesia",
    tahunLulus: "2018",
    lembagaPenempatan: "PT Bank Syariah Bukopin",
    jabatanDps: "Ketua",
    skPengangkatan: "SK-DSN-MUI/IV/2024/022",
    tanggalSk: "2024-04-10",
    masaJabatanMulai: "2024-04-10",
    masaJabatanSelesai: "2029-04-10",
    riwayatJabatan: [],
    sertifikatPelatihan: [
      { nama: "Sertifikasi Aspek Hukum Keuangan Syariah", lembaga: "DSN-MUI", tahun: "2015" }
    ],
    bidangKeahlian: ["Hukum Perdata & Bisnis Syariah", "Sertifikasi Halal"],
    pengalamanProfesional: "Wakil Sekjen MUI Bidang Hukum & HAM, Direktur Eksekutif Indonesia Halal Watch (IHW)."
  }
];

async function main() {
  console.log('Seeding DPS Members...');
  
  // Clear existing DPS first
  await prisma.dpsMember.deleteMany({});
  
  for (const dps of initialDpsList) {
    await prisma.dpsMember.create({
      data: {
        id: dps.id,
        status: dps.status,
        jenisPenugasan: dps.jenisPenugasan,
        tanggalPengajuan: dps.tanggalPengajuan,
        namaLengkap: dps.namaLengkap,
        tempatLahir: dps.tempatLahir,
        tanggalLahir: dps.tanggalLahir,
        jenisKelamin: dps.jenisKelamin,
        kewarganegaraan: dps.kewarganegaraan,
        agama: dps.agama,
        npwp: dps.npwp,
        alamatDomisili: dps.alamatDomisili,
        rtRw: dps.rtRw,
        kelurahan: dps.kelurahan,
        kecamatan: dps.kecamatan,
        kotaKabupaten: dps.kotaKabupaten,
        provinsi: dps.provinsi,
        kodePos: dps.kodePos,
        noTelepon: dps.noTelepon,
        noHp: dps.noHp,
        email: dps.email,
        pendidikanTerakhir: dps.pendidikanTerakhir,
        perguruanTinggi: dps.perguruanTinggi,
        tahunLulus: dps.tahunLulus,
        lembagaPenempatan: dps.lembagaPenempatan,
        jabatanDps: dps.jabatanDps,
        skPengangkatan: dps.skPengangkatan,
        tanggalSk: dps.tanggalSk,
        masaJabatanMulai: dps.masaJabatanMulai,
        masaJabatanSelesai: dps.masaJabatanSelesai,
        riwayatJabatan: dps.riwayatJabatan as any,
        sertifikatPelatihan: dps.sertifikatPelatihan as any,
        bidangKeahlian: dps.bidangKeahlian as any,
        pengalamanProfesional: dps.pengalamanProfesional,
        dokumenFiles: []
      }
    });
  }
  
  console.log('DPS Seeding completed successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
